%% Returns an error message for names that does not fulfill given naming conventions
%
% cs_failure = mes_checkNamingConventions(cs_names,s_pathtemplate) 
% 
% returns a cell array of strings of the same size as cs_names. Entries are 
% either empty (corresponding entry in cs_names is OK) or contains an error 
% message (for the corresponding entry in cs_names).
%
% This function based on an xml-file which could be generated by using
% the ExcelFile 'NamingConventions'
% 
% INPUT:
% ======
% cs_names, cell array of strings, columnvector
%           each entry is filled with a name, that is checked for
%           correctness
% s_pathXmlFile, string,
%           complete path of the corresponding xml file. It is generated
%           by a macro within the corresponding Excel file. It is mandatory
%           to follow the instructions within this Excel file. 
% 
% OUTPUT:
% =======
% cs_failure, cell array of strings, columnvector,
%          If an entry is empty, the corresponding entry in cs_names (same
%          index) is correct.
%          If an entry is not empty, the corresponding entry in cs_names
%          (same index) is not correct. The message will indicate which
%          part of the user defined name-template is not fulfilled. 
%
% NOTE:
% =====
% - This function checks fragment by fragment. Exception: If there are
%   optional fragments, they are concatenated to the 'next' non-optional
%   fragment
% - Separators between fragments are considered as a part of the fragment
%   to the LEFT of the separator. 
% - Follow the rules in the corresponding Excel file to create an xml file,
%   that could be used by this function. Otherwise, this function will 
%   return nothing you could use. 
%
% *************************************************************************
% Copyright:    Model Engineering Solutions
% Date:         $Date: 2020/07/31 16:10:03CEST $
% Revision:     $Rev: 5592 $
% *************************************************************************

function cs_failure = mes_checkNamingConventions(cs_names,s_pathXmlFile)










































































































































































































