% Used to define different color schemas. In the gui only the name of the
% color schema is shown, not its content.
%default color of block and annotation is defined by
%parameter Block.ForegroundColor,
%Block.BackgroundColor,Annotation.BackgroundColor, Annotation.ForegroundColor
%
% NOTE: the last found condition is the condition of this block
 %e.g farschema can be
        %{'type','Block','backgroundcolor','white','',''};...
        %{'blocktype','inport','forgroundcolor','black','',''}
        %then for inport block, its backgound block must be white and its
        %foreground color must be black.

% ------------------------------------------------------------------------------
function colorSchema=mxam_colorSchema_MES_Complex

colorSchema={...
                'BlockType','Inport,DataStoreRead','BackgroundColor','white','ForegroundColor','green','DropShadow','off','ShowName','on';...
                'MaskType','TL_Inport,TL_DataStoreRead','BackgroundColor','white','ForegroundColor','green','DropShadow','off','ShowName','on';...
                'BlockType','Outport,DataStoreWrite','BackgroundColor','white','ForegroundColor','blue','DropShadow','off','ShowName','on';...
                'MaskType', 'TL_Outport','BackgroundColor','white','ForegroundColor','blue','DropShadow','off','ShowName','on';...

%                'code','mxam_BusSelectorDemuxNotAfterInport(#hBlock)','BackgroundColor','white','ForegroundColor','black','DropShadow','off','ShowName','off';...
%                'code','mxam_BusSelectorDemuxAfterInport(#hBlock)','BackgroundColor','white','ForegroundColor','green','DropShadow','off','ShowName','off';...
                
%                'code','mxam_BusCreatorMuxBeforeOutport(#hBlock)','BackgroundColor','white','ForegroundColor','blue','DropShadow','off','ShowName','off';...
                
                'code','mxam_constantGainBlockwithParameter(#hBlock)','BackgroundColor','white','ForegroundColor','lightblue','DropShadow','off','ShowName','off';...
                'code','mxam_constantGainBlockNotwithParameter(#hBlock)','BackgroundColor','white','ForegroundColor','orange','DropShadow','off','ShowName','off';...
                
                'MaskType','CMBlock,DocBlock','BackgroundColor','darkgreen','ForegroundColor','black','DropShadow','off','ShowName','on';...
                'MaskType','Stateflow','BackgroundColor','yellow','ForegroundColor','black','DropShadow','off','ShowName','on';...
                
                'BlockType','Logic,RelationalOperator','BackgroundColor','white','ForegroundColor','gray','DropShadow','off','ShowName','off';...
                'MaskType','Compare To Zero,Detect Change,Detect Decrease,Detect Increase,Detect Rise Nonnegative,Detect Rise Positive','BackgroundColor','white','ForegroundColor','gray','DropShadow','off','ShowName','off';...
                
                'BlockType','TriggerPort,EnablePort','BackgroundColor','white','ForegroundColor','magenta','DropShadow','off','ShowName','on';...
                'BlockType','Interpolation_n-D,PreLookup,Lookup,Lookup2D,Lookup_n-D','BackgroundColor','lightblue','ForegroundColor','black','DropShadow','off','ShowName','on';...
                'MaskType','LookupNDDirect,TL_LookupNDDirect,Lookup Table Dynamic','BackgroundColor','lightblue','ForegroundColor','black','DropShadow','off','ShowName','on';...                
                
                'Name','Version_info','BackgroundColor','yellow','ForegroundColor','black','DropShadow','','ShowName','';... 
                %do not check TL block
                'code','mes_isTLBlock(#hBlock)','BackgroundColor','','ForegroundColor','','DropShadow','','ShowName','';...                
                'code','mxam_isTrueSubsystem(#hBlock) & mes_isReuseableSubsystem(#hBlock)','BackgroundColor','red','ForegroundColor','black','DropShadow','on','ShowName','on';...                
                % do not check blocks inside a lib block
                'code','mes_isBlockLocked(#hBlock)','BackgroundColor','','ForegroundColor','','DropShadow','','ShowName','';...                
                
                %for objects that will not be checked, set the property value to empty
                'type','annotation','BackgroundColor','','ForegroundColor','','DropShadow','','ShowName','';...
                'BlockType','Demux,Mux,BusSelector,BusCreator','BackgroundColor','','ForegroundColor','','DropShadow','off','ShowName','off';...
%                'Type','Block','BackgroundColor','white','ForegroundColor','black','DropShadow','off','ShowName','off';...
                %do not check contents of linked blocks
                'code','mes_isContentOfLibBlock(#hBlock)','BackgroundColor','','ForegroundColor','','DropShadow','','ShowName','';...                
                };