% Used to define different color schemas. In the gui only the name of the
% color schema is shown, not its content.
%parameter Block.ForegroundColor,
%Block.BackgroundColor,Annotation.BackgroundColor, Annotation.ForegroundColor
% ------------------------------------------------------------------------------
function colorSchema=mxam_colorSchema
%color_colorSchema
colorSchema={...
                'BlockType','Inport','BackgroundColor','green','','';...
                'MaskType','TL_Inport','BackgroundColor','green','','';...
                'BlockType','From','BackgroundColor','[128 255 128]','','';...
                'BlockType','DataStoreRead','BackgroundColor','[0 160 0]','','';...
                'MaskType', 'TL_DataStoreRead','BackgroundColor','[0 160 0]','','';...
                'BlockType','Ground,Terminator','BackgroundColor','gray','','';...
                'BlockType','DataStoreWrite','BackgroundColor','[160 0 0]','','';...
                'BlockType','DataStoreMemory','BackgroundColor','[160 0 160]','','';...
                'BlockType','outport','BackgroundColor','[255 66 66]','','';...
                'MaskType', 'TL_Outport','BackgroundColor','[255 66 66]','','';...
                'BlockType','Goto','BackgroundColor','[255 128 128]','','';...
                'BlockType','Constant','BackgroundColor','lightBlue','','';...
                'BlockType','S-Function','BackgroundColor','[128 128 255]','','';...
                'MaskType','CMBlock,DocBlock','BackgroundColor','[255 255 128]','','';...
                'BlockType','If,SwitchCase,Merge','BackgroundColor','orange','','';...
                'BlockType','SignalSpecification,DataTypeConversion','BackgroundColor','[224 224 224]','','';...
                'MaskType','Stateflow','BackgroundColor','[255 255 0]','','';...
                'BlockType','TriggerPort','BackgroundColor','magenta','','';...
                'MaskType','Function-Call Generator','BackgroundColor','magenta','','';...
                'code','mxam_subsystemsWithColor(#hBlock)','BackgroundColor','[128 255 255]','','';...
                'Type','Annotation','ForegroundColor','black','BackgroundColor','white'...
               };
%sw_colorSchema
% colorSchema={'','','','','',''};
%color_mesSchema
% colorSchema={...
%                 'BlockType','Inport,Ground,From,DataStoreRead','BackgroundColor','white','ForegroundColor','green','DropShadow','off','ShowName','on';...
%                 'MaskType','TL_Inport,TL_DataStoreRead','BackgroundColor','white','ForegroundColor','green','DropShadow','off','ShowName','on';...
%                 'BlockType','Outport,Terminator,DataStoreWrite,Goto','BackgroundColor','white','ForegroundColor','blue','DropShadow','off','ShowName','on';...
%                 'MaskType', 'TL_Outport','BackgroundColor','white','ForegroundColor','blue','DropShadow','off','ShowName','on';...
% 
%                 'code','mxam_BusSelectorDemuxNotAfterInport(#hBlock)','BackgroundColor','white','ForegroundColor','black','DropShadow','off','ShowName','off';...
%                 'code','mxam_BusSelectorDemuxAfterInport(#hBlock)','BackgroundColor','white','ForegroundColor','green','DropShadow','off','ShowName','off';...
%                 
%                 'code','mxam_BusCreatorMuxBeforeOutport(#hBlock)','BackgroundColor','white','ForegroundColor','blau','DropShadow','off','ShowName','off';...
%                 
%                 'code','mxam_constantGainBlockwithParameter(#hBlock)','BackgroundColor','white','ForegroundColor','lightblue','DropShadow','off','ShowName','off';...
%                 'code','mxam_constantGainBlockNotwithParameter(#hBlock)','BackgroundColor','white','ForegroundColor','orange','DropShadow','off','ShowName','off';...
%                 
%                 'MaskType','CMBlock,DocBlock','BackgroundColor','darkgreen','ForegroundColor','black','DropShadow','off','ShowName','on';...
%                 'MaskType','Stateflow','BackgroundColor','yellow','ForegroundColor','black','DropShadow','off','ShowName','on';...
%                 
%                 'BlockType','Logic,RelationalOperator','BackgroundColor','white','ForegroundColor','gray','DropShadow','off','ShowName','off';...
%                 'MaskType','Compare To Zero,Detect Change,Detect Decrease,Detect Increase,Detect Rise Nonnegative,Detect Rise Positive','BackgroundColor','white','ForegroundColor','gray','DropShadow','off','ShowName','off';...
%                 
%                 'BlockType','TriggerPort,EnablePort','BackgroundColor','white','ForegroundColor','magenta','DropShadow','off','ShowName','on';...
%                 'BlockType','Interpolation_n-D,PreLookup,Lookup,Lookup2D,Lookup_n-D','BackgroundColor','lightblue','ForegroundColor','black','DropShadow','off','ShowName','on';...
%                 'MaskType','LookupNDDirect,TL_LookupNDDirect,Lookup Table Dynamic','BackgroundColor','lightblue','ForegroundColor','black','DropShadow','off','ShowName','on';...                
%                 
%                 'code','mxam_isTrueSubsystem(#hBlock)','BackgroundColor','white','ForegroundColor','red','DropShadow','on','ShowName','on';...                
%                 
%                 'Type','Block','BackgroundColor','white','ForegroundColor','black','DropShadow','off','ShowName','off';...
%                 };