%% block parameters for misra_slsf_006
%
% cs_items=mxam_misra_slsf_006_checkedParameters
%
% contains all block parameters that will be considered by
% misra_slsf_006_a/_b/_c.
% Returnvalue could be altered manually or could be automatically created
% by running script 'mxam_getToBeCheckedBlockParams'.
%
% INPUT:
%=======
% s_checkName, type:string,

% CALLED BY
% misra_slsf_006_a,
% misra_slsf_006_b
% misra_slsf_006_c

% OUTPUT:
% =======
% cs_items, type: cell array of strings,
%       each row in cs_items represents one block with parameters to be
%       considered and is a cell array of strings itself.
%       These cell arrays consist of three entries:
%       1. Blocktype, type: string,
%       2. Masktype, type: string,
%       3. Parameters to be considered, type: cell array of strings
%
% HELP
% How to configure the parameter list?
% Syntax -
% cs_items={...
% {'<blocktype>' '<masktype>' {'<Attribute name 1>' '<Attribute name 2>' '<Attribute name 3>'.....'<Attribute name n>'}};...
% {'<blocktype>' '<masktype>' {'<Attribute name 1>' '<Attribute name 2>' '<Attribute name 3>'.....'<Attribute name n>'}};...
% };

% Note:- Please donot delete brackets or add extra brackets. This may lead
%        to syntax error and abort the check execution. For further
%        questions contact 'mxam@model-engineers.com'

% PUBLISHING INFORMATION
% *************************************************************************
% Copyright:    Model Engineering Solutions
%**************************************************************************

function cs_items=mxam_misra_slsf_006_checkedParameters(s_checkName)
cs_items = {};

if strcmp(s_checkName,'misra_slsf_006_a')
    
    cs_items={...
        {'SubSystem' 'Fixed-Point State-Space' {'A' 'B' 'C' 'D' 'X0' }};...
        {'SubSystem' 'Ramp' {'slope' 'start' 'X0' }};...
        {'Inport' '' {'Port' 'OutMin' 'OutMax' 'PortDimensions' 'SampleTime' }};...
        {'DataTypeDuplicate' '' {'NumInputPorts' }};...
        {'S-Function' 'Data Type Propagation' {'NumBitsMult' 'NumBitsAdd' 'SlopeMult' 'SlopeAdd' 'BiasMult' 'BiasAdd' }};...
        {'UnitDelay' '' {'InitialCondition' 'SampleTime' 'X0'}};...
        {'Gain' '' {'Gain' 'ParamMin' 'ParamMax' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'DataTypeConversion' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'Sum' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'Outport' '' {'Port' 'OutMin' 'OutMax' 'PortDimensions' 'SampleTime' 'InitialOutput' }};...
        {'SubSystem' 'Transfer Fcn Direct Form II' {'NumCoefVec' 'DenCoefVec' 'vinit' }};...
        {'Mux' '' {'Inputs' }};...
        {'S-Function' 'Tapped Delay Line' {'vinit' 'samptime' 'NumDelays' }};...
        {'SubSystem' 'Transfer Fcn Direct Form II Time Varying' {'vinit' }};...
        {'DotProduct' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Unit Delay Enabled' {'vinit' 'tsamp' }};...
        {'Switch' '' {'Threshold' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'Unit Delay Enabled External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay Enabled Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay Enabled Resettable External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay Resettable External Initial Condition' {'tsamp' }};...
        {'Constant' '' {'Value' 'OutMin' 'OutMax' 'SampleTime' 'FramePeriod' }};...
        {'Logic' '' {'Inputs' 'SampleTime' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled Resettable External RV' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Resettable External RV' {'vinit' 'tsamp' }};...
        {'RelationalOperator' '' {'SampleTime' }};...
        {'SampleTimeMath' '' {'weightValue' }};...
        {'BusCreator' '' {'Inputs' }};...
        {'Delay' '' {'DelayLength' 'DelayLengthUpperLimit' 'InitialCondition' 'SampleTime' }};...
        {'Demux' '' {'Outputs' }};...
        {'DiscreteIntegrator' '' {'gainval' 'InitialCondition' 'SampleTime' 'OutMin' 'OutMax' 'UpperSaturationLimit' 'LowerSaturationLimit' 'StateIdentifier' 'StateStorageClass' 'RTWStateStorageTypeQualifier' }};...
        {'Integrator' '' {'InitialCondition' 'UpperSaturationLimit' 'LowerSaturationLimit' 'AbsoluteTolerance' 'ContinuousStateAttributes' 'WrappedStateUpperValue' 'WrappedStateLowerValue'}};...
        {'Product' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'Saturate' '' {'UpperLimit' 'LowerLimit' 'SampleTime' 'OutMin' 'OutMax' }};...
        {'Scope' '' {'NumInputPorts' 'TimeRange' 'YMin' 'YMax' 'SaveName' 'MaxDataPoints' 'SampleTime' }};...
        {'Derivative' '' {'CoefficientInTFapproximation' }};...
        {'SecondOrderIntegrator' '' {'ICX' 'UpperLimitX' 'LowerLimitX' 'AbsoluteToleranceX' 'ICDXDT' 'UpperLimitDXDT' 'LowerLimitDXDT' 'AbsoluteToleranceDXDT' }};...
        {'SubSystem' 'PID 1dof' {'SampleTime' 'P' 'I' 'D' 'N' 'InitialConditionForIntegrator' 'InitialConditionForFilter' 'UpperSaturationLimit' 'LowerSaturationLimit' 'Kb' 'Kt' 'PParamMin' 'PParamMax' 'IParamMin' 'IParamMax' 'DParamMin' 'DParamMax' 'NParamMin' 'NParamMax' 'KbParamMin' 'KbParamMax' 'KtParamMin' 'KtParamMax' 'POutMin' 'POutMax' 'IOutMin' 'IOutMax' 'DOutMin' 'DOutMax' 'NOutMin' 'NOutMax' 'KbOutMin' 'KbOutMax' 'KtOutMin' 'KtOutMax' 'IntegratorOutMin' 'IntegratorOutMax' 'FilterOutMin' 'FilterOutMax' 'SumOutMin' 'SumOutMax' 'SumI1OutMin' 'SumI1OutMax' 'SumI2OutMin' 'SumI2OutMax' 'SumI3OutMin' 'SumI3OutMax' 'SumDOutMin' 'SumDOutMax' 'SaturationOutMin' 'SaturationOutMax' }};...
        {'SubSystem' 'PID 2dof' {'SampleTime' 'P' 'I' 'D' 'N' 'b' 'c' 'InitialConditionForIntegrator' 'InitialConditionForFilter' 'UpperSaturationLimit' 'LowerSaturationLimit' 'Kb' 'Kt' 'PParamMin' 'PParamMax' 'IParamMin' 'IParamMax' 'DParamMin' 'DParamMax' 'NParamMin' 'NParamMax' 'bParamMin' 'bParamMax' 'cParamMin' 'cParamMax' 'KbParamMin' 'KbParamMax' 'KtParamMin' 'KtParamMax' 'POutMin' 'POutMax' 'IOutMin' 'IOutMax' 'DOutMin' 'DOutMax' 'NOutMin' 'NOutMax' 'bOutMin' 'bOutMax' 'cOutMin' 'cOutMax' 'KbOutMin' 'KbOutMax' 'KtOutMin' 'KtOutMax' 'IntegratorOutMin' 'IntegratorOutMax' 'FilterOutMin' 'FilterOutMax' 'SumOutMin' 'SumOutMax' 'Sum1OutMin' 'Sum1OutMax' 'Sum2OutMin' 'Sum2OutMax' 'Sum3OutMin' 'Sum3OutMax' 'SumI1OutMin' 'SumI1OutMax' 'SumI2OutMin' 'SumI2OutMax' 'SumI3OutMin' 'SumI3OutMax' 'SumDOutMin' 'SumDOutMax' 'SaturationOutMin' 'SaturationOutMax' }};...
        {'StateSpace' '' {'A' 'B' 'C' 'D' 'X0' 'AbsoluteTolerance' }};...
        {'TransferFcn' '' {'Numerator' 'Denominator' 'AbsoluteTolerance' }};...
        {'TransportDelay' '' {'DelayTime' 'InitialOutput' 'BufferSize' 'PadeOrder' }};...
        {'VariableTransportDelay' '' {'MaximumDelay' 'InitialOutput' 'MaximumPoints' 'PadeOrder' 'AbsoluteTolerance' 'ContinuousStateAttributes' }};...
        {'ZeroPole' '' {'Zeros' 'Poles' 'Gain' 'AbsoluteTolerance' 'ContinuousStateAttributes' }};...
        {'Backlash' '' {'BacklashWidth' 'InitialOutput' 'SampleTime' }};...
        {'SubSystem' 'Coulombic and Viscous Friction' {'offset' 'gain' }};...
        {'Signum' '' {'SampleTime' }};...
        {'DeadZone' '' {'LowerValue' 'UpperValue' 'SampleTime' }};...
        {'HitCross' '' {'HitCrossingOffset' 'SampleTime' }};...
        {'Quantizer' '' {'QuantizationInterval' 'SampleTime' }};...
        {'RateLimiter' '' {'RisingSlewLimit' 'FallingSlewLimit' 'InitialCondition' }};...
        {'SubSystem' 'Saturation Dynamic' {'OutMin' 'OutMax' }};...
        {'Relay' '' {'OnSwitchValue' 'OffSwitchValue' 'OnOutputValue' 'OffOutputValue' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'Wrap To Zero' {'Threshold' }};...
        {'SubSystem' 'Difference' {'ICPrevInput' 'OutMin' 'OutMax' }};...
        {'DiscreteTransferFcn' '' {'Numerator' 'Denominator' 'InitialStates' 'InitialDenominatorStates' 'SampleTime' 'NumCoefMin' 'NumCoefMax' 'DenCoefMin' 'DenCoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteZeroPole' '' {'Zeros' 'Poles' 'Gain' 'SampleTime'}};...
        {'SubSystem' 'Discrete Derivative' {'gainval' 'ICPrevScaledInput' 'OutMin' 'OutMax' }};...
        {'DiscreteFir' '' {'Coefficients' 'InitialStates' 'SampleTime' 'CoefMin' 'CoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteFilter' '' {'Numerator' 'Denominator' 'InitialStates' 'InitialDenominatorStates' 'SampleTime' 'NumCoefMin' 'NumCoefMax' 'DenCoefMin' 'DenCoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteStateSpace' '' {'A' 'B' 'C' 'D' 'X0' 'SampleTime' }};...
        {'SubSystem' 'First-Order Hold' {'Ts' }};...
        {'DigitalClock' '' {'SampleTime' }};...
        {'ZeroOrderHold' '' {'SampleTime' }};...
        {'Memory' '' {'X0' }};...
        {'SubSystem' 'First Order Transfer Fcn' {'PoleZ' 'ICPrevOutput' }};...
        {'SubSystem' 'Lead or Lag Compensator' {'PoleZ' 'ZeroZ' 'ICPrevOutput' 'ICPrevInput' }};...
        {'SubSystem' 'Transfer Fcn Real Zero' {'ZeroZ' 'ICPrevInput' }};...
        {'SubSystem' 'Bit Clear' {'iBit' }};...
        {'S-Function' 'Bitwise Operator' {'NumInputPorts' }};...
        {'SubSystem' 'Bit Set' {'iBit' }};...
        {'CombinatorialLogic' '' {'TruthTable' 'SampleTime'}};...
        {'SubSystem' 'Compare To Constant' {'const' }};...
        {'SubSystem' 'Detect Change' {'vinit' }};...
        {'SubSystem' 'Detect Decrease' {'vinit' }};...
        {'SubSystem' 'Detect Increase' {'vinit' }};...
        {'SubSystem' 'Detect Fall Negative' {'vinit' }};...
        {'SubSystem' 'Detect Fall Nonpositive' {'vinit' }};...
        {'SubSystem' 'Detect Rise Nonnegative' {'vinit' }};...
        {'SubSystem' 'Detect Rise Positive' {'vinit' }};...
        {'SubSystem' 'Extract Bits' {'numBits' 'bitIdxRange' }};...
        {'SubSystem' 'Interval Test' {'uplimit' 'lowlimit' }};...
        {'ArithShift' '' {'BitShiftNumber' 'BinPtShiftNumber' }};...
        {'Lookup_n-D' '' {'BreakpointsForDimension1' 'BreakpointsForDimension2' 'BreakpointsForDimension3' 'BreakpointsForDimension4' 'BreakpointsForDimension5' 'BreakpointsForDimension6' 'BreakpointsForDimension7' 'BreakpointsForDimension8' 'BreakpointsForDimension9' 'BreakpointsForDimension10' 'BreakpointsForDimension11' 'BreakpointsForDimension12' 'BreakpointsForDimension13' 'BreakpointsForDimension14' 'BreakpointsForDimension15' 'BreakpointsForDimension16' 'BreakpointsForDimension17' 'BreakpointsForDimension18' 'BreakpointsForDimension19' 'BreakpointsForDimension20' 'BreakpointsForDimension21' 'BreakpointsForDimension22' 'BreakpointsForDimension23' 'BreakpointsForDimension24' 'BreakpointsForDimension25' 'BreakpointsForDimension26' 'BreakpointsForDimension27' 'BreakpointsForDimension28' 'BreakpointsForDimension29' 'BreakpointsForDimension30' 'Table' 'MaximumIndicesForEachDimension' }};...
        {'SubSystem' 'Sine and Cosine' {'NumDataPoints' 'OutputWordLength' }};...
        {'SubSystem' 'Cosine' {'NumDataPoints' 'OutputWordLength' }};...
        {'LookupNDDirect' '' {'NumberOfTableDimensions' 'Table' 'SampleTime' 'TableMin' 'TableMax'}};...
        {'Interpolation_n-D' '' {'NumberOfTableDimensions' 'Table' 'NumSelectionDims' 'SampleTime' 'OutMin' 'OutMax' 'TableMin' 'TableMax'}};...
        {'PreLookup' '' {'BreakpointsData' }};...
        {'SubSystem' 'Sine' {'NumDataPoints' 'OutputWordLength' }};...
        {'Abs' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Algebraic Constraint' {'z0' }};...
        {'InitialCondition' '' {'Value' 'SampleTime' }};...
        {'Assignment' '' {'SampleTime' }};...
        {'Bias' '' {'Bias' }};...
        {'ComplexToMagnitudeAngle' '' {'SampleTime' }};...
        {'ComplexToRealImag' '' {'SampleTime' }};...
        {'Find' '' {'NumberOfInputDimensions' 'SampleTime' }};...
        {'MagnitudeAngleToComplex' '' {'ConstantPart' 'NumberOfIterations' 'SampleTime' }};...
        {'Math' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'MinMax' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'MinMax Running Resettable' {'vinit' }};...
        {'PermuteDimensions' '' {'Order' }};...
        {'Polyval' '' {'Coefs' }};...
        {'RealImagToComplex' '' {'ConstantPart' 'SampleTime' }};...
        {'Sqrt' '' {'SampleTime' 'OutMin' 'OutMax' 'Iterations' }};...
        {'Reshape' '' {'OutputDimensions' }};...
        {'Rounding' '' {'SampleTime' }};...
        {'Sin' '' {'Amplitude' 'Bias' 'Frequency' 'Phase' 'SampleTime' }};...
        {'Trigonometry' '' {'NumberOfIterations' 'SampleTime' }};...
        {'UnaryMinus' '' {'SampleTime' }};...
        {'Assertion' '' {'SampleTime' }};...
        {'SubSystem' 'Checks_Gradient' {'gradient' }};...
        {'SubSystem' 'Checks_SGap' {'max' 'min' }};...
        {'SubSystem' 'Checks_SRange' {'max' 'min' }};...
        {'SubSystem' 'Checks_Resolution' {'resolution' }};...
        {'SubSystem' 'Checks_SMin' {'min' }};...
        {'SubSystem' 'Checks_SMax' {'max' }};...
        {'SubSystem' 'Timed Linearization' {'LinearizationTime' 'SampleTime' }};...
        {'TriggerPort' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Triggered Linearization' {'SampleTime' }};...
        {'EnablePort' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'ForIterator' '' {'IterationLimit' }};...
        {'S-Function' 'Function-Call Generator' {'sample_time'}};...
        {'If' '' {'IfExpression' 'ElseIfExpressions' 'SampleTime' }};...
        {'SwitchCase' '' {'CaseConditions' 'SampleTime' }};...
        {'RateTransition' '' {'X0' }};...
        {'SignalSpecification' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'DataStoreMemory' '' {'InitialValue' 'OutMin' 'OutMax' }};...
        {'DataStoreRead' '' {'SampleTime' }};...
        {'DataStoreWrite' '' {'SampleTime'}};...
        {'MultiPortSwitch' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'ManualSwitch' '' {'SampleTime' }};...
        {'Merge' '' {'InitialOutput' }};...
        {'Selector' '' {'SampleTime'}};...
        {'ToFile' '' {'SampleTime' }};...
        {'ToWorkspace' '' {'SampleTime' }};...
        {'SubSystem' 'XY scope.' {'xmin' 'xmax' 'ymin' 'ymax' 'st' }};...
        {'SubSystem' 'Band-Limited White Noise.' {'Cov' 'Ts' }};...
        {'SubSystem' 'Counter Free-Running' { 'tsamp' }};...
        {'SubSystem' 'Counter Limited' {'uplimit' 'tsamp' }};...
        {'SubSystem' 'Enumerated Constant' {'Value' 'SampleTime' }};...
        {'DiscretePulseGenerator' '' {'Amplitude' 'Period' 'PulseWidth' 'PhaseDelay' 'SampleTime'}};...
        {'Step' '' {'Time' 'Before' 'After' 'SampleTime'}};...
        {'SubSystem' 'Repeating table' {'rep_seq_t' 'rep_seq_y' }};...
        {'Lookup' '' {'InputValues' 'Table' }};...
        {'SubSystem' 'Repeating Sequence Interpolated' {'OutValues' 'TimeValues' 'tsamp' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Repeating Sequence Stair' {'OutValues' 'tsamp' 'OutMin' 'OutMax' }};...
        {'SignalGenerator' '' {'Amplitude' 'Frequency' }};...
        {'UniformRandomNumber' '' {'Minimum' 'Maximum' 'Seed' 'SampleTime' }};...
        {'MATLABFcn' '' { 'SampleTime'}};...
        {'SubSystem' 'TL_BitClear' {'bitindex' }};...
        {'SubSystem' 'TL_BitSet' {'bitindex' }};...
        {'S-Function' 'TL_BitwiseOperator' {'bitmask.value' }};...
        {'Constant' 'TL_Constant' {'dt' 'output.value' }};...
        {'S-Function' 'TL_CustomCode' {'dt' 'param.value' 'state.initial'}};...
        {'DataStoreMemory' 'TL_DataStoreMemory' {'output.initial' }};...
        {'DataStoreRead' 'TL_DataStoreRead' {'dt' }};...
        {'DataStoreWrite' 'TL_DataStoreWrite' {'dt' }};...
        {'LookupNDDirect' 'TL_LookupNDDirect' {'table.value' }};...
        {'DiscreteTransferFcn' 'TL_DiscreteTransferFcn' {'denom.value' 'dt' 'num.value' }};...
        {'DiscreteFilter' 'TL_DiscreteFilter' {'denom.value' 'dt' 'num.value' }};...
        {'DiscreteStateSpace' 'TL_DiscreteStateSpace' {'amatrix.value' 'bmatrix.value' 'cmatrix.value' 'dmatrix.value' 'dt' 'state.initial' }};...
        {'DiscreteIntegrator' 'TL_DiscreteIntegrator' {'dt' 'lowerlimit.value' 'state.initial' 'upperlimit.value' }};...
        {'SubSystem' 'TL_JKFlipFlop' {'output.initial' }};...
        {'SubSystem' 'TL_SRFlipFlop' {'output.initial' }};...
        {'DiscreteFilter' 'TL_FIRFilter' { 'coeff.value' 'dt' }};...
        {'Gain' 'TL_Gain' { 'gain.value' }};...
        {'Lookup_n-D' 'TL_Lookup1D' {'input.value' 'table.value' }};...
        {'Lookup_n-D' 'TL_Lookup2D' {'col.value' 'table.value' 'row.value'}};...
        {'Merge' 'TL_Merge' { 'output.initial' }};...
        {'PreLookup' 'TL_PreLookup' {'input.value' }};...
        {'RateLimiter' 'TL_RateLimiter' {'fslewrate.value' 'rslewrate.value' }};...
        {'Relay' 'TL_Relay' {'offoutput.value' 'offswitch.value' 'onoutput.value' 'onswitch.value' }};...
        {'Saturate' 'TL_Saturate' {'lowerlimit.value' 'upperlimit.value' }};...
        {'ArithShift' 'TL_ArithShift' {'bitshiftnumber' }};...
        {'SubSystem' 'TL_Sink' {'dt' }};...
        {'Switch' 'TL_Switch' {'threshold.value' }};...
        {'UnitDelay' 'TL_UnitDelay' {'dt' 'state.initial' }};...
        {'SubSystem' 'TL_UnitDelayRE' {'dt' 'state.initial'}};...
        };
    if ~verLessThan('matlab', '9.4')
        cs_items{1} = {'SubSystem' 'Fixed-Point State-Space' {'A' 'B' 'C' 'D' 'InitialCondition' }};
        cs_items{2} = {'SubSystem' 'Ramp' {'slope' 'start' 'InitialOutput' }};
    end
elseif strcmp(s_checkName,'misra_slsf_006_b')
    cs_items={...
        {'SubSystem' 'Fixed-Point State-Space' {'A' 'B' 'C' 'D' 'X0' }};...
        {'SubSystem' 'Ramp' {'slope' 'start' 'X0' }};...
        {'Inport' '' {'Port' 'OutMin' 'OutMax' 'PortDimensions' 'SampleTime' }};...
        {'DataTypeDuplicate' '' {'NumInputPorts' }};...
        {'S-Function' 'Data Type Propagation' {'NumBitsMult' 'NumBitsAdd' 'SlopeMult' 'SlopeAdd' 'BiasMult' 'BiasAdd' }};...
        {'UnitDelay' '' {'SampleTime' 'X0'}};...
        {'Gain' '' {'Gain' 'ParamMin' 'ParamMax' 'ParamDataTypeStr' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'DataTypeConversion' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'Sum' '' {'Inputs' 'AccumDataTypeStr' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'Outport' '' {'Port' 'OutMin' 'OutMax' 'PortDimensions' 'SampleTime' 'InitialOutput' }};...
        {'SubSystem' 'Transfer Fcn Direct Form II' {'NumCoefVec' 'DenCoefVec' 'vinit' }};...
        {'Mux' '' {'Inputs' }};...
        {'S-Function' 'Tapped Delay Line' {'vinit' 'samptime' 'NumDelays' }};...
        {'SubSystem' 'Transfer Fcn Direct Form II Time Varying' {'vinit' }};...
        {'DotProduct' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Unit Delay Enabled' {'vinit' 'tsamp' }};...
        {'Switch' '' {'Threshold' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'Unit Delay Enabled External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay Enabled Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay Enabled Resettable External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay Resettable External Initial Condition' {'tsamp' }};...
        {'Constant' '' {'Value' 'OutMin' 'OutMax' 'SampleTime' 'FramePeriod' }};...
        {'Logic' '' {'Inputs' 'SampleTime' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled Resettable External RV' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Resettable External RV' {'vinit' 'tsamp' }};...
        {'RelationalOperator' '' {'SampleTime' }};...
        {'SampleTimeMath' '' {'weightValue' }};...
        {'BusCreator' '' {'Inputs' }};...
        {'BusSelector' '' {'OutputSignals' }};...
        {'Delay' '' {'DelayLength' 'DelayLengthUpperLimit' 'InitialCondition' 'SampleTime' }};...
        {'Demux' '' {'Outputs' }};...
        {'DiscreteIntegrator' '' {'gainval' 'InitialCondition' 'SampleTime' 'OutMin' 'OutMax' 'UpperSaturationLimit' 'LowerSaturationLimit' 'StateIdentifier' 'StateStorageClass' 'RTWStateStorageTypeQualifier' }};...
        {'Integrator' '' {'InitialCondition' 'UpperSaturationLimit' 'LowerSaturationLimit' 'AbsoluteTolerance' 'ContinuousStateAttributes' 'WrappedStateUpperValue' 'WrappedStateLowerValue'}};...
        {'Product' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'Saturate' '' {'UpperLimit' 'LowerLimit' 'SampleTime' 'OutMin' 'OutMax' }};...
        {'Scope' '' {'NumInputPorts' 'TimeRange' 'YMin' 'YMax' 'SaveName' 'MaxDataPoints' 'SampleTime' }};...
        {'Derivative' '' {'CoefficientInTFapproximation' }};...
        {'SecondOrderIntegrator' '' {'ICX' 'UpperLimitX' 'LowerLimitX' 'AbsoluteToleranceX' 'ICDXDT' 'UpperLimitDXDT' 'LowerLimitDXDT' 'AbsoluteToleranceDXDT' }};...
        {'SubSystem' 'PID 1dof' {'SampleTime' 'P' 'I' 'D' 'N' 'InitialConditionForIntegrator' 'InitialConditionForFilter' 'UpperSaturationLimit' 'LowerSaturationLimit' 'Kb' 'Kt' 'PParamMin' 'PParamMax' 'IParamMin' 'IParamMax' 'DParamMin' 'DParamMax' 'NParamMin' 'NParamMax' 'KbParamMin' 'KbParamMax' 'KtParamMin' 'KtParamMax' 'POutMin' 'POutMax' 'IOutMin' 'IOutMax' 'DOutMin' 'DOutMax' 'NOutMin' 'NOutMax' 'KbOutMin' 'KbOutMax' 'KtOutMin' 'KtOutMax' 'IntegratorOutMin' 'IntegratorOutMax' 'FilterOutMin' 'FilterOutMax' 'SumOutMin' 'SumOutMax' 'SumI1OutMin' 'SumI1OutMax' 'SumI2OutMin' 'SumI2OutMax' 'SumI3OutMin' 'SumI3OutMax' 'SumDOutMin' 'SumDOutMax' 'SaturationOutMin' 'SaturationOutMax' }};...
        {'SubSystem' 'PID 2dof' {'SampleTime' 'P' 'I' 'D' 'N' 'b' 'c' 'InitialConditionForIntegrator' 'InitialConditionForFilter' 'UpperSaturationLimit' 'LowerSaturationLimit' 'Kb' 'Kt' 'PParamMin' 'PParamMax' 'IParamMin' 'IParamMax' 'DParamMin' 'DParamMax' 'NParamMin' 'NParamMax' 'bParamMin' 'bParamMax' 'cParamMin' 'cParamMax' 'KbParamMin' 'KbParamMax' 'KtParamMin' 'KtParamMax' 'POutMin' 'POutMax' 'IOutMin' 'IOutMax' 'DOutMin' 'DOutMax' 'NOutMin' 'NOutMax' 'bOutMin' 'bOutMax' 'cOutMin' 'cOutMax' 'KbOutMin' 'KbOutMax' 'KtOutMin' 'KtOutMax' 'IntegratorOutMin' 'IntegratorOutMax' 'FilterOutMin' 'FilterOutMax' 'SumOutMin' 'SumOutMax' 'Sum1OutMin' 'Sum1OutMax' 'Sum2OutMin' 'Sum2OutMax' 'Sum3OutMin' 'Sum3OutMax' 'SumI1OutMin' 'SumI1OutMax' 'SumI2OutMin' 'SumI2OutMax' 'SumI3OutMin' 'SumI3OutMax' 'SumDOutMin' 'SumDOutMax' 'SaturationOutMin' 'SaturationOutMax' }};...
        {'StateSpace' '' {'A' 'B' 'C' 'D' 'X0' 'AbsoluteTolerance' }};...
        {'TransferFcn' '' {'Numerator' 'Denominator' 'AbsoluteTolerance' }};...
        {'TransportDelay' '' {'DelayTime' 'InitialOutput' 'BufferSize' 'PadeOrder' }};...
        {'VariableTransportDelay' '' {'MaximumDelay' 'InitialOutput' 'MaximumPoints' 'PadeOrder' 'AbsoluteTolerance' 'ContinuousStateAttributes' }};...
        {'ZeroPole' '' {'Zeros' 'Poles' 'Gain' 'AbsoluteTolerance' 'ContinuousStateAttributes' }};...
        {'Backlash' '' {'BacklashWidth' 'InitialOutput' 'SampleTime' }};...
        {'SubSystem' 'Coulombic and Viscous Friction' {'offset' 'gain' }};...
        {'Signum' '' {'SampleTime' }};...
        {'DeadZone' '' {'LowerValue' 'UpperValue' 'SampleTime' }};...
        {'HitCross' '' {'HitCrossingOffset' 'SampleTime' }};...
        {'Quantizer' '' {'QuantizationInterval' 'SampleTime' }};...
        {'RateLimiter' '' {'RisingSlewLimit' 'FallingSlewLimit' 'InitialCondition' }};...
        {'SubSystem' 'Saturation Dynamic' {'OutMin' 'OutMax' }};...
        {'Relay' '' {'OnSwitchValue' 'OffSwitchValue' 'OnOutputValue' 'OffOutputValue' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'Wrap To Zero' {'Threshold' }};...
        {'SubSystem' 'Difference' {'ICPrevInput' 'OutMin' 'OutMax' }};...
        {'DiscreteTransferFcn' '' {'Numerator' 'Denominator' 'InitialStates' 'InitialDenominatorStates' 'SampleTime' 'NumCoefMin' 'NumCoefMax' 'DenCoefMin' 'DenCoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteZeroPole' '' {'Zeros' 'Poles' 'Gain' 'SampleTime'}};...
        {'SubSystem' 'Discrete Derivative' {'gainval' 'ICPrevScaledInput' 'OutMin' 'OutMax' }};...
        {'DiscreteFir' '' {'Coefficients' 'InitialStates' 'SampleTime' 'CoefMin' 'CoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteFilter' '' {'Numerator' 'Denominator' 'InitialStates' 'InitialDenominatorStates' 'SampleTime' 'NumCoefMin' 'NumCoefMax' 'DenCoefMin' 'DenCoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteStateSpace' '' {'A' 'B' 'C' 'D' 'X0' 'SampleTime' }};...
        {'SubSystem' 'First-Order Hold' {'Ts' }};...
        {'DigitalClock' '' {'SampleTime' }};...
        {'ZeroOrderHold' '' {'SampleTime' }};...
        {'Memory' '' {'X0' }};...
        {'SubSystem' 'First Order Transfer Fcn' {'PoleZ' 'ICPrevOutput' }};...
        {'SubSystem' 'Lead or Lag Compensator' {'PoleZ' 'ZeroZ' 'ICPrevOutput' 'ICPrevInput' }};...
        {'SubSystem' 'Transfer Fcn Real Zero' {'ZeroZ' 'ICPrevInput' }};...
        {'SubSystem' 'Bit Clear' {'iBit' }};...
        {'S-Function' 'Bitwise Operator' {'NumInputPorts' }};...
        {'SubSystem' 'Bit Set' {'iBit' }};...
        {'CombinatorialLogic' '' {'TruthTable' 'SampleTime'}};...
        {'SubSystem' 'Compare To Constant' {'const' }};...
        {'SubSystem' 'Detect Change' {'vinit' }};...
        {'SubSystem' 'Detect Decrease' {'vinit' }};...
        {'SubSystem' 'Detect Increase' {'vinit' }};...
        {'SubSystem' 'Detect Fall Negative' {'vinit' }};...
        {'SubSystem' 'Detect Fall Nonpositive' {'vinit' }};...
        {'SubSystem' 'Detect Rise Nonnegative' {'vinit' }};...
        {'SubSystem' 'Detect Rise Positive' {'vinit' }};...
        {'SubSystem' 'Extract Bits' {'numBits' 'bitIdxRange' }};...
        {'SubSystem' 'Interval Test' {'uplimit' 'lowlimit' }};...
        {'ArithShift' '' {'BitShiftNumber' 'BinPtShiftNumber' }};...
        {'Lookup_n-D' '' {'BreakpointsForDimension1' 'BreakpointsForDimension2' 'BreakpointsForDimension3' 'BreakpointsForDimension4' 'BreakpointsForDimension5' 'BreakpointsForDimension6' 'BreakpointsForDimension7' 'BreakpointsForDimension8' 'BreakpointsForDimension9' 'BreakpointsForDimension10' 'BreakpointsForDimension11' 'BreakpointsForDimension12' 'BreakpointsForDimension13' 'BreakpointsForDimension14' 'BreakpointsForDimension15' 'BreakpointsForDimension16' 'BreakpointsForDimension17' 'BreakpointsForDimension18' 'BreakpointsForDimension19' 'BreakpointsForDimension20' 'BreakpointsForDimension21' 'BreakpointsForDimension22' 'BreakpointsForDimension23' 'BreakpointsForDimension24' 'BreakpointsForDimension25' 'BreakpointsForDimension26' 'BreakpointsForDimension27' 'BreakpointsForDimension28' 'BreakpointsForDimension29' 'BreakpointsForDimension30' 'Table' 'MaximumIndicesForEachDimension' }};...
        {'SubSystem' 'Sine and Cosine' {'NumDataPoints' 'OutputWordLength' }};...
        {'SubSystem' 'Cosine' {'NumDataPoints' 'OutputWordLength' }};...
        {'LookupNDDirect' '' {'NumberOfTableDimensions' 'Table' 'SampleTime' 'TableMin' 'TableMax'}};...
        {'Interpolation_n-D' '' {'NumberOfTableDimensions' 'Table' 'NumSelectionDims' 'SampleTime' 'OutMin' 'OutMax' 'TableMin' 'TableMax'}};...
        {'PreLookup' '' {'BreakpointsData' }};...
        {'SubSystem' 'Sine' {'NumDataPoints' 'OutputWordLength' }};...
        {'Abs' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Algebraic Constraint' {'z0' }};...
        {'InitialCondition' '' {'Value' 'SampleTime' }};...
        {'Assignment' '' {'SampleTime' }};...
        {'Bias' '' {'Bias' }};...
        {'ComplexToMagnitudeAngle' '' {'SampleTime' }};...
        {'ComplexToRealImag' '' {'SampleTime' }};...
        {'Find' '' {'NumberOfInputDimensions' 'SampleTime' }};...
        {'MagnitudeAngleToComplex' '' {'ConstantPart' 'NumberOfIterations' 'SampleTime' }};...
        {'Math' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'MinMax' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'MinMax Running Resettable' {'vinit' }};...
        {'PermuteDimensions' '' {'Order' }};...
        {'Polyval' '' {'Coefs' }};...
        {'RealImagToComplex' '' {'ConstantPart' 'SampleTime' }};...
        {'Sqrt' '' {'SampleTime' 'OutMin' 'OutMax' 'Iterations' }};...
        {'Reshape' '' {'OutputDimensions' }};...
        {'Rounding' '' {'SampleTime' }};...
        {'Sin' '' {'Amplitude' 'Bias' 'Frequency' 'Phase' 'SampleTime' }};...
        {'Trigonometry' '' {'NumberOfIterations' 'SampleTime' }};...
        {'UnaryMinus' '' {'SampleTime' }};...
        {'Assertion' '' {'SampleTime' }};...
        {'SubSystem' 'Checks_Gradient' {'gradient' }};...
        {'SubSystem' 'Checks_SGap' {'max' 'min' }};...
        {'SubSystem' 'Checks_SRange' {'max' 'min' }};...
        {'SubSystem' 'Checks_Resolution' {'resolution' }};...
        {'SubSystem' 'Checks_SMin' {'min' }};...
        {'SubSystem' 'Checks_SMax' {'max' }};...
        {'SubSystem' 'Timed Linearization' {'LinearizationTime' 'SampleTime' }};...
        {'TriggerPort' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Triggered Linearization' {'SampleTime' }};...
        {'EnablePort' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'ForIterator' '' {'IterationLimit' }};...
        {'S-Function' 'Function-Call Generator' {'sample_time'}};...
        {'If' '' {'SampleTime' }};...
        {'SwitchCase' '' {'SampleTime' }};...
        {'RateTransition' '' {'X0' }};...
        {'SignalSpecification' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'DataStoreMemory' '' {'InitialValue' 'OutMin' 'OutMax' }};...
        {'DataStoreRead' '' {'SampleTime' }};...
        {'DataStoreWrite' '' {'SampleTime'}};...
        {'MultiPortSwitch' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'ManualSwitch' '' {'SampleTime' }};...
        {'Merge' '' {'InitialOutput' }};...
        {'Selector' '' {'SampleTime'}};...
        {'ToFile' '' {'SampleTime' }};...
        {'ToWorkspace' '' {'SampleTime' }};...
        {'SubSystem' 'XY scope.' {'xmin' 'xmax' 'ymin' 'ymax' 'st' }};...
        {'SubSystem' 'Band-Limited White Noise.' {'Cov' 'Ts' }};...
        {'SubSystem' 'Counter Free-Running' { 'tsamp' }};...
        {'SubSystem' 'Counter Limited' {'uplimit' 'tsamp' }};...
        {'SubSystem' 'Enumerated Constant' {'Value' 'SampleTime' }};...
        {'DiscretePulseGenerator' '' {'Amplitude' 'Period' 'PulseWidth' 'PhaseDelay' 'SampleTime'}};...
        {'Step' '' {'Time' 'Before' 'After' 'SampleTime'}};...
        {'SubSystem' 'Repeating table' {'rep_seq_t' 'rep_seq_y' }};...
        {'Lookup' '' {'InputValues' 'Table' }};...
        {'SubSystem' 'Repeating Sequence Interpolated' {'OutValues' 'TimeValues' 'tsamp' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Repeating Sequence Stair' {'OutValues' 'tsamp' 'OutMin' 'OutMax' }};...
        {'SignalGenerator' '' {'Amplitude' 'Frequency' }};...
        {'UniformRandomNumber' '' {'Minimum' 'Maximum' 'Seed' 'SampleTime' }};...
        {'MATLABFcn' '' { 'SampleTime'}};...
        {'SubSystem' 'TL_BitClear' {'bitindex' }};...
        {'SubSystem' 'TL_BitSet' {'bitindex' }};...
        {'S-Function' 'TL_BitwiseOperator' {'bitmask.value' }};...
        {'Constant' 'TL_Constant' {'dt' 'output.value' }};...
        {'S-Function' 'TL_CustomCode' {'dt' 'param.value' 'state.initial'}};...
        {'DataStoreMemory' 'TL_DataStoreMemory' {'output.initial' }};...
        {'DataStoreRead' 'TL_DataStoreRead' {'dt' }};...
        {'DataStoreWrite' 'TL_DataStoreWrite' {'dt' }};...
        {'LookupNDDirect' 'TL_LookupNDDirect' {'table.value' }};...
        {'DiscreteTransferFcn' 'TL_DiscreteTransferFcn' {'denom.value' 'dt' 'num.value' }};...
        {'DiscreteFilter' 'TL_DiscreteFilter' {'denom.value' 'dt' 'num.value' }};...
        {'DiscreteStateSpace' 'TL_DiscreteStateSpace' {'amatrix.value' 'bmatrix.value' 'cmatrix.value' 'dmatrix.value' 'dt' 'state.initial' }};...
        {'DiscreteIntegrator' 'TL_DiscreteIntegrator' {'dt' 'lowerlimit.value' 'state.initial' 'upperlimit.value' }};...
        {'SubSystem' 'TL_JKFlipFlop' {'output.initial' }};...
        {'SubSystem' 'TL_SRFlipFlop' {'output.initial' }};...
        {'DiscreteFilter' 'TL_FIRFilter' { 'coeff.value' 'dt' }};...
        {'Gain' 'TL_Gain' { 'gain.value' }};...
        {'Lookup_n-D' 'TL_Lookup1D' {'input.value' 'table.value' }};...
        {'Lookup_n-D' 'TL_Lookup2D' {'col.value' 'table.value' 'row.value'}};...
        {'Merge' 'TL_Merge' { 'output.initial' }};...
        {'PreLookup' 'TL_PreLookup' {'input.value' }};...
        {'RateLimiter' 'TL_RateLimiter' {'fslewrate.value' 'rslewrate.value' }};...
        {'Relay' 'TL_Relay' {'offoutput.value' 'offswitch.value' 'onoutput.value' 'onswitch.value' }};...
        {'Saturate' 'TL_Saturate' {'lowerlimit.value' 'upperlimit.value' }};...
        {'ArithShift' 'TL_ArithShift' {'bitshiftnumber' }};...
        {'SubSystem' 'TL_Sink' {'dt' }};...
        {'Switch' 'TL_Switch' {'threshold.value' }};...
        {'UnitDelay' 'TL_UnitDelay' {'dt' 'state.initial' }};...
        {'SubSystem' 'TL_UnitDelayRE' {'dt' 'state.initial'}};...
        };
    if ~verLessThan('matlab', '9.4')
        cs_items{1} = {'SubSystem' 'Fixed-Point State-Space' {'A' 'B' 'C' 'D' 'InitialCondition' }};
        cs_items{2} = {'SubSystem' 'Ramp' {'slope' 'start' 'InitialOutput' }};
    end
elseif strcmp(s_checkName,'misra_slsf_006_c')
    cs_items={...
        {'SubSystem' 'Fixed-Point State-Space' {'A' 'B' 'C' 'D' 'X0' }};...
        {'SubSystem' 'Ramp' {'slope' 'start' 'X0' }};...
        {'Inport' '' {'Port' 'OutMin' 'OutMax' 'PortDimensions' 'SampleTime' }};...
        {'DataTypeDuplicate' '' {'NumInputPorts' }};...
        {'S-Function' 'Data Type Propagation' {'NumBitsMult' 'NumBitsAdd' 'SlopeMult' 'SlopeAdd' 'BiasMult' 'BiasAdd' }};...
        {'UnitDelay' '' {'SampleTime' 'X0'}};...
        {'Gain' '' {'Gain' 'ParamMin' 'ParamMax' 'ParamDataTypeStr' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'DataTypeConversion' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'Sum' '' {'Inputs' 'AccumDataTypeStr' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'Outport' '' {'Port' 'OutMin' 'OutMax' 'PortDimensions' 'SampleTime' 'InitialOutput' }};...
        {'SubSystem' 'Transfer Fcn Direct Form II' {'NumCoefVec' 'DenCoefVec' 'vinit' }};...
        {'Mux' '' {'Inputs' }};...
        {'S-Function' 'Tapped Delay Line' {'vinit' 'samptime' 'NumDelays' }};...
        {'SubSystem' 'Transfer Fcn Direct Form II Time Varying' {'vinit' }};...
        {'DotProduct' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Unit Delay Enabled' {'vinit' 'tsamp' }};...
        {'Switch' '' {'Threshold' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'Unit Delay Enabled External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay Enabled Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay Enabled Resettable External Initial Condition' {'tsamp' }};...
        {'SubSystem' 'Unit Delay Resettable External Initial Condition' {'tsamp' }};...
        {'Constant' '' {'Value' 'OutMin' 'OutMax' 'SampleTime' 'FramePeriod' }};...
        {'Logic' '' {'Inputs' 'SampleTime' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Enabled Resettable External RV' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Resettable' {'vinit' 'tsamp' }};...
        {'SubSystem' 'Unit Delay With Preview Resettable External RV' {'vinit' 'tsamp' }};...
        {'RelationalOperator' '' {'SampleTime' }};...
        {'SampleTimeMath' '' {'weightValue' }};...
        {'BusCreator' '' {'Inputs' }};...
        {'BusSelector' '' {'OutputSignals' }};...
        {'Delay' '' {'DelayLength' 'DelayLengthUpperLimit' 'InitialCondition' 'SampleTime' }};...
        {'Demux' '' {'Outputs' }};...
        {'DiscreteIntegrator' '' {'gainval' 'InitialCondition' 'SampleTime' 'OutMin' 'OutMax' 'UpperSaturationLimit' 'LowerSaturationLimit' 'StateIdentifier' 'StateStorageClass' 'RTWStateStorageTypeQualifier' }};...
        {'Integrator' '' {'InitialCondition' 'UpperSaturationLimit' 'LowerSaturationLimit' 'AbsoluteTolerance' 'ContinuousStateAttributes' 'WrappedStateUpperValue' 'WrappedStateLowerValue'}};...
        {'Product' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'Saturate' '' {'UpperLimit' 'LowerLimit' 'SampleTime' 'OutMin' 'OutMax' }};...
        {'Scope' '' {'NumInputPorts' 'TimeRange' 'YMin' 'YMax' 'SaveName' 'MaxDataPoints' 'SampleTime' }};...
        {'Derivative' '' {'CoefficientInTFapproximation' }};...
        {'SecondOrderIntegrator' '' {'ICX' 'UpperLimitX' 'LowerLimitX' 'AbsoluteToleranceX' 'ICDXDT' 'UpperLimitDXDT' 'LowerLimitDXDT' 'AbsoluteToleranceDXDT' }};...
        {'SubSystem' 'PID 1dof' {'SampleTime' 'P' 'I' 'D' 'N' 'InitialConditionForIntegrator' 'InitialConditionForFilter' 'UpperSaturationLimit' 'LowerSaturationLimit' 'Kb' 'Kt' 'PParamMin' 'PParamMax' 'IParamMin' 'IParamMax' 'DParamMin' 'DParamMax' 'NParamMin' 'NParamMax' 'KbParamMin' 'KbParamMax' 'KtParamMin' 'KtParamMax' 'POutMin' 'POutMax' 'IOutMin' 'IOutMax' 'DOutMin' 'DOutMax' 'NOutMin' 'NOutMax' 'KbOutMin' 'KbOutMax' 'KtOutMin' 'KtOutMax' 'IntegratorOutMin' 'IntegratorOutMax' 'FilterOutMin' 'FilterOutMax' 'SumOutMin' 'SumOutMax' 'SumI1OutMin' 'SumI1OutMax' 'SumI2OutMin' 'SumI2OutMax' 'SumI3OutMin' 'SumI3OutMax' 'SumDOutMin' 'SumDOutMax' 'SaturationOutMin' 'SaturationOutMax' }};...
        {'SubSystem' 'PID 2dof' {'SampleTime' 'P' 'I' 'D' 'N' 'b' 'c' 'InitialConditionForIntegrator' 'InitialConditionForFilter' 'UpperSaturationLimit' 'LowerSaturationLimit' 'Kb' 'Kt' 'PParamMin' 'PParamMax' 'IParamMin' 'IParamMax' 'DParamMin' 'DParamMax' 'NParamMin' 'NParamMax' 'bParamMin' 'bParamMax' 'cParamMin' 'cParamMax' 'KbParamMin' 'KbParamMax' 'KtParamMin' 'KtParamMax' 'POutMin' 'POutMax' 'IOutMin' 'IOutMax' 'DOutMin' 'DOutMax' 'NOutMin' 'NOutMax' 'bOutMin' 'bOutMax' 'cOutMin' 'cOutMax' 'KbOutMin' 'KbOutMax' 'KtOutMin' 'KtOutMax' 'IntegratorOutMin' 'IntegratorOutMax' 'FilterOutMin' 'FilterOutMax' 'SumOutMin' 'SumOutMax' 'Sum1OutMin' 'Sum1OutMax' 'Sum2OutMin' 'Sum2OutMax' 'Sum3OutMin' 'Sum3OutMax' 'SumI1OutMin' 'SumI1OutMax' 'SumI2OutMin' 'SumI2OutMax' 'SumI3OutMin' 'SumI3OutMax' 'SumDOutMin' 'SumDOutMax' 'SaturationOutMin' 'SaturationOutMax' }};...
        {'StateSpace' '' {'A' 'B' 'C' 'D' 'X0' 'AbsoluteTolerance' }};...
        {'TransferFcn' '' {'Numerator' 'Denominator' 'AbsoluteTolerance' }};...
        {'TransportDelay' '' {'DelayTime' 'InitialOutput' 'BufferSize' 'PadeOrder' }};...
        {'VariableTransportDelay' '' {'MaximumDelay' 'InitialOutput' 'MaximumPoints' 'PadeOrder' 'AbsoluteTolerance' 'ContinuousStateAttributes' }};...
        {'ZeroPole' '' {'Zeros' 'Poles' 'Gain' 'AbsoluteTolerance' 'ContinuousStateAttributes' }};...
        {'Backlash' '' {'BacklashWidth' 'InitialOutput' 'SampleTime' }};...
        {'SubSystem' 'Coulombic and Viscous Friction' {'offset' 'gain' }};...
        {'Signum' '' {'SampleTime' }};...
        {'DeadZone' '' {'LowerValue' 'UpperValue' 'SampleTime' }};...
        {'HitCross' '' {'HitCrossingOffset' 'SampleTime' }};...
        {'Quantizer' '' {'QuantizationInterval' 'SampleTime' }};...
        {'RateLimiter' '' {'RisingSlewLimit' 'FallingSlewLimit' 'InitialCondition' }};...
        {'SubSystem' 'Saturation Dynamic' {'OutMin' 'OutMax' }};...
        {'Relay' '' {'OnSwitchValue' 'OffSwitchValue' 'OnOutputValue' 'OffOutputValue' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'Wrap To Zero' {'Threshold' }};...
        {'SubSystem' 'Difference' {'ICPrevInput' 'OutMin' 'OutMax' }};...
        {'DiscreteTransferFcn' '' {'Numerator' 'Denominator' 'InitialStates' 'InitialDenominatorStates' 'SampleTime' 'NumCoefMin' 'NumCoefMax' 'DenCoefMin' 'DenCoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteZeroPole' '' {'Zeros' 'Poles' 'Gain' 'SampleTime'}};...
        {'SubSystem' 'Discrete Derivative' {'gainval' 'ICPrevScaledInput' 'OutMin' 'OutMax' }};...
        {'DiscreteFir' '' {'Coefficients' 'InitialStates' 'SampleTime' 'CoefMin' 'CoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteFilter' '' {'Numerator' 'Denominator' 'InitialStates' 'InitialDenominatorStates' 'SampleTime' 'NumCoefMin' 'NumCoefMax' 'DenCoefMin' 'DenCoefMax' 'OutMin' 'OutMax'}};...
        {'DiscreteStateSpace' '' {'A' 'B' 'C' 'D' 'X0' 'SampleTime' }};...
        {'SubSystem' 'First-Order Hold' {'Ts' }};...
        {'DigitalClock' '' {'SampleTime' }};...
        {'ZeroOrderHold' '' {'SampleTime' }};...
        {'Memory' '' {'X0' }};...
        {'SubSystem' 'First Order Transfer Fcn' {'PoleZ' 'ICPrevOutput' }};...
        {'SubSystem' 'Lead or Lag Compensator' {'PoleZ' 'ZeroZ' 'ICPrevOutput' 'ICPrevInput' }};...
        {'SubSystem' 'Transfer Fcn Real Zero' {'ZeroZ' 'ICPrevInput' }};...
        {'SubSystem' 'Bit Clear' {'iBit' }};...
        {'S-Function' 'Bitwise Operator' {'NumInputPorts' }};...
        {'SubSystem' 'Bit Set' {'iBit' }};...
        {'CombinatorialLogic' '' {'TruthTable' 'SampleTime'}};...
        {'SubSystem' 'Compare To Constant' {'const' }};...
        {'SubSystem' 'Detect Change' {'vinit' }};...
        {'SubSystem' 'Detect Decrease' {'vinit' }};...
        {'SubSystem' 'Detect Increase' {'vinit' }};...
        {'SubSystem' 'Detect Fall Negative' {'vinit' }};...
        {'SubSystem' 'Detect Fall Nonpositive' {'vinit' }};...
        {'SubSystem' 'Detect Rise Nonnegative' {'vinit' }};...
        {'SubSystem' 'Detect Rise Positive' {'vinit' }};...
        {'SubSystem' 'Extract Bits' {'numBits' 'bitIdxRange' }};...
        {'SubSystem' 'Interval Test' {'uplimit' 'lowlimit' }};...
        {'ArithShift' '' {'BitShiftNumber' 'BinPtShiftNumber' }};...
        {'Lookup_n-D' '' {'BreakpointsForDimension1' 'BreakpointsForDimension2' 'BreakpointsForDimension3' 'BreakpointsForDimension4' 'BreakpointsForDimension5' 'BreakpointsForDimension6' 'BreakpointsForDimension7' 'BreakpointsForDimension8' 'BreakpointsForDimension9' 'BreakpointsForDimension10' 'BreakpointsForDimension11' 'BreakpointsForDimension12' 'BreakpointsForDimension13' 'BreakpointsForDimension14' 'BreakpointsForDimension15' 'BreakpointsForDimension16' 'BreakpointsForDimension17' 'BreakpointsForDimension18' 'BreakpointsForDimension19' 'BreakpointsForDimension20' 'BreakpointsForDimension21' 'BreakpointsForDimension22' 'BreakpointsForDimension23' 'BreakpointsForDimension24' 'BreakpointsForDimension25' 'BreakpointsForDimension26' 'BreakpointsForDimension27' 'BreakpointsForDimension28' 'BreakpointsForDimension29' 'BreakpointsForDimension30' 'Table' 'MaximumIndicesForEachDimension' }};...
        {'SubSystem' 'Sine and Cosine' {'NumDataPoints' 'OutputWordLength' }};...
        {'SubSystem' 'Cosine' {'NumDataPoints' 'OutputWordLength' }};...
        {'LookupNDDirect' '' {'NumberOfTableDimensions' 'Table' 'SampleTime' 'TableMin' 'TableMax'}};...
        {'Interpolation_n-D' '' {'NumberOfTableDimensions' 'Table' 'NumSelectionDims' 'SampleTime' 'OutMin' 'OutMax' 'TableMin' 'TableMax'}};...
        {'PreLookup' '' {'BreakpointsData' }};...
        {'SubSystem' 'Sine' {'NumDataPoints' 'OutputWordLength' }};...
        {'Abs' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Algebraic Constraint' {'z0' }};...
        {'InitialCondition' '' {'Value' 'SampleTime' }};...
        {'Assignment' '' {'SampleTime' }};...
        {'Bias' '' {'Bias' }};...
        {'ComplexToMagnitudeAngle' '' {'SampleTime' }};...
        {'ComplexToRealImag' '' {'SampleTime' }};...
        {'Find' '' {'NumberOfInputDimensions' 'SampleTime' }};...
        {'MagnitudeAngleToComplex' '' {'ConstantPart' 'NumberOfIterations' 'SampleTime' }};...
        {'Math' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'MinMax' '' {'Inputs' 'OutMin' 'OutMax' 'SampleTime' }};...
        {'SubSystem' 'MinMax Running Resettable' {'vinit' }};...
        {'PermuteDimensions' '' {'Order' }};...
        {'Polyval' '' {'Coefs' }};...
        {'RealImagToComplex' '' {'ConstantPart' 'SampleTime' }};...
        {'Sqrt' '' {'SampleTime' 'OutMin' 'OutMax' 'Iterations' }};...
        {'Reshape' '' {'OutputDimensions' }};...
        {'Rounding' '' {'SampleTime' }};...
        {'Sin' '' {'Amplitude' 'Bias' 'Frequency' 'Phase' 'SampleTime' }};...
        {'Trigonometry' '' {'NumberOfIterations' 'SampleTime' }};...
        {'UnaryMinus' '' {'SampleTime' }};...
        {'Assertion' '' {'SampleTime' }};...
        {'SubSystem' 'Checks_Gradient' {'gradient' }};...
        {'SubSystem' 'Checks_SGap' {'max' 'min' }};...
        {'SubSystem' 'Checks_SRange' {'max' 'min' }};...
        {'SubSystem' 'Checks_Resolution' {'resolution' }};...
        {'SubSystem' 'Checks_SMin' {'min' }};...
        {'SubSystem' 'Checks_SMax' {'max' }};...
        {'SubSystem' 'Timed Linearization' {'LinearizationTime' 'SampleTime' }};...
        {'TriggerPort' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Triggered Linearization' {'SampleTime' }};...
        {'EnablePort' '' {'SampleTime' 'OutMin' 'OutMax' }};...
        {'ForIterator' '' {'IterationLimit' }};...
        {'S-Function' 'Function-Call Generator' {'sample_time'}};...
        {'If' '' {'SampleTime' }};...
        {'SwitchCase' '' {'SampleTime' }};...
        {'RateTransition' '' {'X0' }};...
        {'SignalSpecification' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'DataStoreMemory' '' {'InitialValue' 'OutMin' 'OutMax' }};...
        {'DataStoreRead' '' {'SampleTime' }};...
        {'DataStoreWrite' '' {'SampleTime'}};...
        {'MultiPortSwitch' '' {'OutMin' 'OutMax' 'SampleTime' }};...
        {'ManualSwitch' '' {'SampleTime' }};...
        {'Merge' '' {'InitialOutput' }};...
        {'Selector' '' {'SampleTime'}};...
        {'ToFile' '' {'SampleTime' }};...
        {'ToWorkspace' '' {'SampleTime' }};...
        {'SubSystem' 'XY scope.' {'xmin' 'xmax' 'ymin' 'ymax' 'st' }};...
        {'SubSystem' 'Band-Limited White Noise.' {'Cov' 'Ts' }};...
        {'SubSystem' 'Counter Free-Running' { 'tsamp' }};...
        {'SubSystem' 'Counter Limited' {'uplimit' 'tsamp' }};...
        {'SubSystem' 'Enumerated Constant' {'Value' 'SampleTime' }};...
        {'DiscretePulseGenerator' '' {'Amplitude' 'Period' 'PulseWidth' 'PhaseDelay' 'SampleTime'}};...
        {'Step' '' {'Time' 'Before' 'After' 'SampleTime'}};...
        {'SubSystem' 'Repeating table' {'rep_seq_t' 'rep_seq_y' }};...
        {'Lookup' '' {'InputValues' 'Table' }};...
        {'SubSystem' 'Repeating Sequence Interpolated' {'OutValues' 'TimeValues' 'tsamp' 'OutMin' 'OutMax' }};...
        {'SubSystem' 'Repeating Sequence Stair' {'OutValues' 'tsamp' 'OutMin' 'OutMax' }};...
        {'SignalGenerator' '' {'Amplitude' 'Frequency' }};...
        {'UniformRandomNumber' '' {'Minimum' 'Maximum' 'Seed' 'SampleTime' }};...
        {'MATLABFcn' '' { 'SampleTime'}};...
        {'SubSystem' 'TL_BitClear' {'bitindex' }};...
        {'SubSystem' 'TL_BitSet' {'bitindex' }};...
        {'S-Function' 'TL_BitwiseOperator' {'bitmask.value' }};...
        {'Constant' 'TL_Constant' {'dt' 'output.value' }};...
        {'S-Function' 'TL_CustomCode' {'dt' 'param.value' 'state.initial'}};...
        {'DataStoreMemory' 'TL_DataStoreMemory' {'output.initial' }};...
        {'DataStoreRead' 'TL_DataStoreRead' {'dt' }};...
        {'DataStoreWrite' 'TL_DataStoreWrite' {'dt' }};...
        {'LookupNDDirect' 'TL_LookupNDDirect' {'table.value' }};...
        {'DiscreteTransferFcn' 'TL_DiscreteTransferFcn' {'denom.value' 'dt' 'num.value' }};...
        {'DiscreteFilter' 'TL_DiscreteFilter' {'denom.value' 'dt' 'num.value' }};...
        {'DiscreteStateSpace' 'TL_DiscreteStateSpace' {'amatrix.value' 'bmatrix.value' 'cmatrix.value' 'dmatrix.value' 'dt' 'state.initial' }};...
        {'DiscreteIntegrator' 'TL_DiscreteIntegrator' {'dt' 'lowerlimit.value' 'state.initial' 'upperlimit.value' }};...
        {'SubSystem' 'TL_JKFlipFlop' {'output.initial' }};...
        {'SubSystem' 'TL_SRFlipFlop' {'output.initial' }};...
        {'DiscreteFilter' 'TL_FIRFilter' { 'coeff.value' 'dt' }};...
        {'Gain' 'TL_Gain' { 'gain.value' }};...
        {'Lookup_n-D' 'TL_Lookup1D' {'input.value' 'table.value' }};...
        {'Lookup_n-D' 'TL_Lookup2D' {'col.value' 'table.value' 'row.value'}};...
        {'Merge' 'TL_Merge' { 'output.initial' }};...
        {'PreLookup' 'TL_PreLookup' {'input.value' }};...
        {'RateLimiter' 'TL_RateLimiter' {'fslewrate.value' 'rslewrate.value' }};...
        {'Relay' 'TL_Relay' {'offoutput.value' 'offswitch.value' 'onoutput.value' 'onswitch.value' }};...
        {'Saturate' 'TL_Saturate' {'lowerlimit.value' 'upperlimit.value' }};...
        {'ArithShift' 'TL_ArithShift' {'bitshiftnumber' }};...
        {'SubSystem' 'TL_Sink' {'dt' }};...
        {'Switch' 'TL_Switch' {'threshold.value' }};...
        {'UnitDelay' 'TL_UnitDelay' {'dt' 'state.initial' }};...
        {'SubSystem' 'TL_UnitDelayRE' {'dt' 'state.initial'}};...
        };
    if ~verLessThan('matlab', '9.4')
        cs_items{1} = {'SubSystem' 'Fixed-Point State-Space' {'A' 'B' 'C' 'D' 'InitialCondition' }};
        cs_items{2} = {'SubSystem' 'Ramp' {'slope' 'start' 'InitialOutput' }};
    end
end